# Copyright (C) 2017 Chris Liebert

[package]
name = "examplelib"
version = "0.1.2"
authors = ["Chris Liebert <cbert745@gmail.com>"]

[dependencies]
libc = "0.2.29"

[lib]
name = "examplelib"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
