# Copyright (C) 2017 Chris Liebert

[package]
name = "examplelib"
version = "0.1.2"
authors = ["Chris Liebert <cbert745@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.29"

[build-dependencies]
genbind = { path = '../..' }

[lib]
name = "examplelib"
path = "lib.rs"
crate-type = ["dylib", "staticlib", "rlib"]
